# Generated by Django 6.0.1 on 2026-02-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodcontainer',
            name='classroom',
            field=models.CharField(blank=True, choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd'), ('F', 'e'), ('G', 'g'), ('H', 'h')], max_length=1, null=True),
        ),
    ]
