# Generated by Django 6.0.1 on 2026-01-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_rename_porfile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teachers_field',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('MA', 'Math'), ('PH', 'Phyiscs'), ('CH', 'Chemist'), ('BI', 'Biology')], max_length=2, null=True),
        ),
    ]
