# Generated by Django 6.0.1 on 2026-02-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_periodcontainer_classroom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='periodcontainer',
            unique_together={('teachers', 'day', 'period', 'classroom')},
        ),
    ]
