# Generated by Django 6.0.1 on 2026-02-02 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_alter_periodcontainer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teachersFill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.profile')),
            ],
        ),
    ]
