# Generated by Django 6.0.1 on 2026-01-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_time_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='period',
            field=models.IntegerField(blank=True, choices=[(1, '1st Period'), (2, '2nd Period'), (3, '3rd Period'), (4, '4th Period'), (5, '5th Period'), (6, '6th Period')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('day', 'period')},
        ),
        migrations.DeleteModel(
            name='Time_Table',
        ),
    ]
