# Generated by Django 6.0.1 on 2026-01-31 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_profile_day_profile_period_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='day',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='period',
        ),
        migrations.CreateModel(
            name='Time_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('period', models.IntegerField(choices=[(1, '1st Period'), (2, '2nd Period'), (3, '3rd Period'), (4, '4th Period'), (5, '5th Period'), (6, '6th Period')])),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.profile')),
            ],
            options={
                'unique_together': {('teachers', 'day', 'period')},
            },
        ),
    ]
